# DEFAULT PROJECT PROFILE
#
# Add local config to _quarto.yml.local

project:
  output-dir: _output
  render:
    - index.qmd
  resources:
    - sample-franklin.png

format:
  art-html: default

keep-tex: true


# PDF engine

#pdf-engine: xelatex
pdf-engine-opt: -shell-escape

# Disable tinytex if already installed
#latex-tinytex: false
