project:
  output-dir: _output
  render:
    - index.qmd
  resources:
    - sample-franklin.png

format:
  art-html: default

keep-tex: true

### LOCAL CONFIGURATION
#
# Add these to _quarto.yml.local
# DO NOT enable it in this file.

# Select PDF engine:

#pdf-engine: latexmk
#pdf-engine: xelatex
#pdf-engine-opt: -shell-escape

# disable tinytex if already installed
#latex-tinytex: false
